### ISSUE TITLE
frm_managerDahsboard.cs: Enhancing the upcoming activity label and messages, reminders and todo next activity sections in the form

### ISSUE THREAD

**Issue by demeshFernando** [demeshFernando/bloodBankManagementSystem#9]
**Introduction.**
In here there are several labels are available in the form and the customization required to do the work will be discussed here.

**Description**
- [ ] Upcoming activity heading will showcase the most recent activity that will going to be due from the list. to do that first fileter the activity which has the most minimum dates to be due from the considering date. 
- [ ] and if several activities have been chosen then get the priority level of those activities if available. 
- [ ] if those activity didn't have any priority level then get the created date of that activity and match its difference which has the more difference should be published through this method. and if there are several chosen activities, 
- [ ] then you can publish any of the activity from the chosen bulk. 
- [ ] if there are several activities which has the same priority level then get the activity which has the largest difference between the published date and the due date of the chosen activity. which activity has the largest gap should be displayed in the panel. 
 
- [ ] The messages, reminders and todo event label is also reserved to show the activity or chosen activities description. 
- [ ] Now for example let's say that there is no activity or messages, reminders and todo event to showcase in here. then just clear the label texts and do not keep them with any messages. 

- [ ] the form should have to refresh from each and every one second to check for messages and reminders that are need to be updated. in that timer it will get constantly checked for newly dueing messages, reminder, activities, todo event and inform it to the user the informing method is as follows
- message body: message or body descrption, 
- message header: BBMS - {Reminder, Messages - {from}, Activity, TODO event}
- message buttons - Mark as read, remind me in {1 Hour, 2 Hours, at the evening or morning, remind me tomorrow}
- [ ] keep in mind even if the user chose 1 hour, 2 hour, at the evening or morning or remind me tomorrow the program needs to calculate the time and update the time of the reminder needs to be happen. and then because the timer is running the message will be shown at the correct time.             

**Altenatives**
In here depending on the activity the moving form will be different, 
- [ ] If the activity actually an activity it is OK to show a normal massage as discussed immeadiately above. 
- [ ] If the activity is a message, then the form should have these buttons, 
- Reply, Close, Cancel
- Form fields: Reply text area. 
- other are normal as usual. the form design will added soon.
- [ ] If the form is a reminder then the design is just as described above in the general section end.      

**Additional context**
